# Site settings
title: Lingfeng's Blog
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Persional BLog For Joy&Fun"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: bcheung92
github_username:  bcheung92
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
